### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by MathiasRenner** [kns-it/Docker-BlueSpice-Wiki#2]
This project is not working.

When I use the docker-compose file including the mysql  DB, I get this error when I point with my browser to the specific port on localhost:

`A database query error has occurred. This may indicate a bug in the software.`

The logs say:

`mysql_1      | 2018-06-24T10:40:28.796444Z 8 [Note] Access denied for user 'root'@'localhost' (using password: NO)`

When I exec into the bluespice container and connect to the DB with the mysql client and the root pw it just works. Where's the error?

**Comment by prskr** [comment]
I can reproduce the behavior you mentioned.
I'm not sure why the problem occurs might be related to the health check of the container (wiki container tries already to run some migrations before the database is ready) or either the setup or the update script are doing some weird stuff.

I'll have a look in the upcoming days and update this issue as soon as I fixed the problem.
